"""Decision records: render a session as a Markdown ADR or as JSON."""

from __future__ import annotations

import json
from typing import Any

from . import __version__


def _cell(text: Any) -> str:
    """Make arbitrary text safe inside a Markdown table cell."""
    s = str(text).replace("\r", " ").replace("\n", " ")
    return s.replace("|", "\\|")


def _line(text: Any) -> str:
    """Collapse line breaks so free text cannot break Markdown structure."""
    return " ".join(str(text).split())


def _num(x: float | None) -> str:
    return "—" if x is None else f"{x:g}"


def _pct(x: float) -> str:
    return f"{x * 100:.1f}%"


def to_json(dec: dict, matrix: dict, analysis: dict | None) -> str:
    return json.dumps(
        {
            "format_version": 1,
            "generated_by": f"mcp-decision-lab {__version__}",
            "decision": dec,
            "matrix": matrix,
            "analysis": analysis,
        },
        indent=2,
        ensure_ascii=False,
    )


def to_markdown(dec: dict, matrix: dict, analysis: dict | None) -> str:
    out: list[str] = []
    add = out.append
    crits = matrix["criteria"]
    options = dec["options"]

    add(f"# Decision record: {_line(dec['question'])}")
    add("")
    if analysis is None:
        status = f"**{matrix['status']}** — {len(matrix['missing_cells'])} cell(s) still unscored"
    elif analysis["winner"]:
        status = f"recommendation: **{analysis['winner']}** ({analysis['robustness']})"
    else:
        status = f"**tie** between {', '.join(analysis['tied'])}"
    add("| | |")
    add("| --- | --- |")
    add(f"| Decision id | `{dec['id']}` |")
    add(f"| Outcome | {status} |")
    add(f"| Created | {dec.get('created_at', '')} |")
    add(f"| Last updated | {dec.get('updated_at', '')} |")
    add(f"| Generated by | mcp-decision-lab {__version__} |")
    add("")

    add("## Criteria")
    add("")
    add("| Criterion | Weight | Scoring direction |")
    add("| --- | ---: | --- |")
    for c in crits:
        direction = (
            "higher raw score is better"
            if c["higher_is_better"]
            else "lower raw score is better (effective = 10 − raw)"
        )
        add(f"| {_cell(c['name'])} | {c['weight']:g} ({_pct(c['weight'])}) | {direction} |")
    add("")

    add("## Scores")
    add("")
    add("Raw scores on a 0–10 scale; the total is the weighted sum of effective scores.")
    add("")
    add("| Option | " + " | ".join(_cell(c["name"]) for c in crits) + " | Total |")
    add("| --- | " + " | ".join("---:" for _ in crits) + " | ---: |")
    for o in options:
        row = matrix["matrix"][o]
        vals = [_num(row[c["name"]]["score"]) if row[c["name"]] else "—" for c in crits]
        add(f"| {_cell(o)} | " + " | ".join(vals) + f" | **{matrix['totals'][o]:g}** |")
    add("")
    if matrix["missing_cells"]:
        add(
            "Unscored cells: "
            + ", ".join(f"{m['option']} / {m['criterion']}" for m in matrix["missing_cells"])
            + "."
        )
        add("")

    add("## Rationales")
    add("")
    for o in options:
        add(f"### {_line(o)}")
        add("")
        for c in crits:
            cell = matrix["matrix"][o][c["name"]]
            if cell is None:
                add(f"- **{_line(c['name'])}** — not scored yet")
            else:
                add(f"- **{_line(c['name'])}** — {cell['score']:g}/10: {_line(cell['rationale'])}")
        add("")

    if analysis is None:
        add("## Analysis")
        add("")
        add("Not available until every cell is scored.")
        add("")
        return "\n".join(out)

    add("## Ranking")
    add("")
    for r in analysis["ranking"]:
        add(f"{r['rank']}. **{r['option']}** — {r['total']:g}")
    add("")
    if analysis["winner"]:
        add(f"Margin between 1st and 2nd: **{analysis['margin']:g}**.")
        add("")

    add("## Recommendation")
    add("")
    add("> " + _line(analysis["recommendation"]))
    add("")

    add("## Robustness")
    add("")
    add(f"Verdict: **{analysis['robustness']}**")
    add("")
    checks = analysis.get("robustness_checks")
    if checks:
        for key, label in (("weights", "Weights"), ("scores", "Scores"), ("monte_carlo", "Monte Carlo")):
            ch = checks[key]
            if ch["passed"] is None:
                mark = "skipped"
            else:
                mark = "pass" if ch["passed"] else "FAIL"
            extra = ""
            if key == "weights" and ch["failing_criteria"]:
                extra = " — failing: " + ", ".join(ch["failing_criteria"])
            if key == "scores" and ch["failing_cells"]:
                extra = " — failing: " + ", ".join(ch["failing_cells"])
            if key == "monte_carlo" and ch["win_probability"] is not None:
                extra = f" — winner ranks 1st in {_pct(ch['win_probability'])}"
            add(f"- {label}: {mark} ({ch['rule']}){extra}")
        add("")

    add("### Weight sensitivity")
    add("")
    if analysis["winner"]:
        add("| Criterion | Weight | Winner flips at | Direction | New winner | Within ±50%? |")
        add("| --- | ---: | ---: | --- | --- | --- |")
        for e in analysis["sensitivity"]:
            f = e["flip"]
            if f is None:
                add(f"| {_cell(e['criterion'])} | {e['weight']:g} | never | — | — | — |")
            else:
                add(
                    f"| {_cell(e['criterion'])} | {e['weight']:g} | {f['flip_weight']:g} | "
                    f"{f['direction']} | {_cell(f['new_winner'])} | "
                    f"{'yes' if f['within_50pct_band'] else 'no'} |"
                )
    else:
        add("| Criterion | Weight | Raising the weight favors | Lowering it favors |")
        add("| --- | ---: | --- | --- |")
        for e in analysis["sensitivity"]:
            tb = e.get("tie_break")
            if tb is None:
                add(f"| {_cell(e['criterion'])} | {e['weight']:g} | no effect | no effect |")
            else:
                add(
                    f"| {_cell(e['criterion'])} | {e['weight']:g} | "
                    f"{_cell(', '.join(tb['raise_weight_favors']))} | "
                    f"{_cell(', '.join(tb['lower_weight_favors']))} |"
                )
    add("")

    ss = analysis["score_sensitivity"]
    add("### Score sensitivity")
    add("")
    if not analysis["winner"]:
        add(ss.get("note", ""))
    elif not ss["most_fragile"]:
        add("No single score change within 0–10 can change the winner.")
    else:
        add(
            f"{ss['flippable_cells']} of {ss['cells_total']} cells can change the winner on "
            "their own. Each row is the threshold the score must cross."
        )
        add("")
        add("| Cell | Current | Winner changes if | Change needed | New winner | Rationale |")
        add("| --- | ---: | --- | ---: | --- | --- |")
        for c in ss["most_fragile"]:
            add(
                f"| {_cell(c['option'])} / {_cell(c['criterion'])} | {c['current_score']:g} | "
                f"{c['direction']} {c['flip_score']:g} | {c['change_needed']:g} | "
                f"{_cell(c['new_winner'])} | {_cell(c['rationale'])} |"
            )
    add("")

    mc = analysis.get("monte_carlo")
    add("### Monte Carlo")
    add("")
    if mc is None:
        add("Skipped (simulations = 0).")
    else:
        add(
            f"{mc['simulations']} joint perturbations (seed {mc['seed']}): weights drawn "
            f"from a Dirichlet centred on the chosen weights (concentration "
            f"{mc['weight_concentration']:g}), every score ±{mc['score_noise']:g}."
        )
        add("")
        add("| Option | P(rank 1) | Expected rank | Total, 5th–95th percentile |")
        add("| --- | ---: | ---: | --- |")
        for o in options:
            s = mc["options"][o]
            add(
                f"| {_cell(o)} | {_pct(s['win_probability'])} | {s['expected_rank']:g} | "
                f"{s['total_p05']:g} – {s['total_p95']:g} |"
            )
    add("")
    return "\n".join(out)
